### ISSUE TITLE
New editor suggestion

### ISSUE THREAD

**Issue by dvorapa** [jbrandwood/EditWith#3]
What about Brackets (http://brackets.io/)?

**Comment by lfpjohn** [comment]
I'd never heard of it until you mentioned it. I'll take a look to see if it can be supported.

**Comment by jbrandwood** [comment]
OK, support for Brackets has been checked-in, and everything seems to work, except that it won't open up files in a new 2nd/3rd/etc window, because Brackets doesn't seem to support that.

I'm afraid that you'll have to compile it yourself if you want to use it right now.

I'm still waiting to hear from the Brackets developers as to whether there is a command line option that I can use to open files in a new window.

**Comment by dvorapa** [comment]
Great :thumbsup:
